# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGEyYzE4N2Q1OTNjY2M5NDhmZDg1ZTg4ZjYxYjJmYTIyNWZmM2FhZjJiNzEwY2U2ZDY5Yzg5MmY1MzI1ZDY1MDBmOTQ0Nzg2ZjkzMGJjMTU2MmRkYjBiZDBkNTk5ZjNhN2UyOWEyOTk2M2VhMDQ0MmE3ZTE2M2NlMjAzODAxMGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
